# Generated by Django 5.0.4 on 2024-04-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet'),
        ('app', '0003_product'),
    ]

    operations = [
    ]
