# Generated by Django 5.0.4 on 2024-04-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.provider'),
            preserve_default=False,
        ),
    ]
