# Generated by Django 5.0.4 on 2024-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vets',
            field=models.ManyToManyField(to='app.vet'),
        ),
    ]
