# Generated by Django 5.0.4 on 2024-04-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pet_vets'),
        ('app', '0008_product_provider'),
    ]

    operations = [
    ]
