# Generated by Django 5.0.4 on 2024-04-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_0008_pet_vets_0008_product_provider'),
        ('app', '0009_sale'),
    ]

    operations = [
    ]
