# Generated by Django 5.0.4 on 2024-04-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vets',
        ),
    ]
